services: 
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5434:5434"
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=upload_test
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
